name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: puctalenthub
  AZURE_WEBAPP_PACKAGE_PATH: "${{ github.workspace }}/myapp"
  DOTNET_SDK_URL: "https://download.visualstudio.microsoft.com/download/pr/0a1b3cbd-b4af-4d0d-9ed7-0054f0e200b4/4bcc533c66379caaa91770236667aacb/dotnet-sdk-8.0.204-linux-x64.tar.gz"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install .NET Core SDK from custom URL
        run: |
          curl -o dotnet.tar.gz ${{ env.DOTNET_SDK_URL }}
          mkdir -p "$HOME/dotnet" && tar zxf dotnet.tar.gz -C "$HOME/dotnet"
          echo "$HOME/dotnet" >> $GITHUB_PATH
          echo 'DOTNET_ROOT=$HOME/dotnet' >> $GITHUB_ENV
          dotnet --version

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build src/TalentHub/TalentHub.csproj --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish src/TalentHub/TalentHub.csproj -c Release -o ${{ github.workspace }}/myapp
          ls -la ${{ github.workspace }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Verify artifact download
        run: |
          ls -la -v1 ${{ github.workspace }}
          if [ $? -ne 0 ]; then
            echo "Error: Artifact .net-app not found or corrupted."
            exit 1
          fi

      - name: List contents of the artifact directory
        run: ls -la ${{ github.workspace }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}
